<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import MonacoPane from './MonacoPane.vue'
import {
  initProjectFs, isTextPath, listFiles, readText, removeFile, renameFile,
  writeBinary, writeText, type ProjectFile,
} from './projectFs'
import { AsciiTeXCompiler } from './compiler'
import type { SourceSyncMap } from './syncMap'

const files = ref<ProjectFile[]>([])
const activePath = ref('/main.tex')
const editorValue = ref('')
const preview = ref('Starting AsciiTeX…')
const status = ref<'loading' | 'ready' | 'building' | 'error'>('loading')
const statusText = ref('Loading Pyodide')
const canvasWidth = ref(96)
const sidebarOpen = ref(true)
const autoCompile = ref(true)
const editorWidth = ref(520)
const workspaceRef = ref<HTMLElement>()
const monacoPaneRef = ref<InstanceType<typeof MonacoPane>>()
const paperStageRef = ref<HTMLElement>()
const previewPreRef = ref<HTMLElement>()
const syncMap = ref<SourceSyncMap>({ outputToSource: [], sourceToOutput: {} })
const copyState = ref<'idle' | 'copied' | 'error'>('idle')
const dirty = ref(false)
const installAvailable = ref(false)
const installedApp = ref(false)
const tourStep = ref(-1)
const tourStyle = ref<Record<string, string>>({})
const tourPlacement = ref<'right' | 'left' | 'bottom'>('right')
const compiler = new AsciiTeXCompiler()
let installPrompt: BeforeInstallPromptEvent | undefined
let saveTimer: ReturnType<typeof setTimeout> | undefined
let compileTimer: ReturnType<typeof setTimeout> | undefined
let buildGeneration = 0

interface BeforeInstallPromptEvent extends Event {
  prompt(): Promise<void>
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed'; platform: string }>
}

// Published project and legal links.
const githubUrl = 'https://github.com/thomasliebig/asciitexstudio'
const imprintUrl = 'https://tapekuna.ai/#impressum'
const tourStorageKey = 'asciitex-studio-tour-complete-v1'
const tourSteps = [
  { target: '[data-tour="files"]', placement: 'right' as const, title: 'Your project files', text: 'Manage the main TeX document, bibliography, images, and other assets here. Everything stays locally in your browser.' },
  { target: '[data-tour="editor"]', placement: 'bottom' as const, title: 'Write AsciiTeX', text: 'Edit the selected text file in Monaco. Syntax highlighting and automatic compilation help you iterate quickly.' },
  { target: '[data-tour="splitter"]', placement: 'left' as const, title: 'Make room where needed', text: 'Drag this divider horizontally to balance source code and rendered output.' },
  { target: '[data-tour="preview"]', placement: 'bottom' as const, title: 'Unicode output', text: 'The result is generated by AsciiTeX in Pyodide. Double-click output and source lines to jump between them.' },
  { target: '[data-tour="actions"]', placement: 'bottom' as const, title: 'Compile and export', text: 'Toggle automatic compilation, compile manually, export the active file, or install the studio as a browser app.' },
]
const activeTour = computed(() => tourStep.value >= 0 ? tourSteps[tourStep.value] : undefined)

const activeFile = computed(() => files.value.find(file => file.path === activePath.value))
const texFiles = computed(() => files.value.filter(file => file.path.endsWith('.tex')))
const language = computed(() => {
  const extension = activePath.value.split('.').pop()?.toLowerCase()
  return ({ tex: 'asciitex', bib: 'bibtex', json: 'json', py: 'python', md: 'markdown' } as Record<string, string>)[extension ?? ''] ?? 'plaintext'
})

function iconFor(path: string): string {
  const ext = path.split('.').pop()?.toLowerCase()
  if (ext === 'tex') return 'TEX'
  if (ext === 'bib') return 'BIB'
  if (['png', 'jpg', 'jpeg', 'gif', 'webp'].includes(ext ?? '')) return 'IMG'
  return 'TXT'
}

function shortName(path: string): string { return path.replace(/^\//, '') }

async function refreshFiles(): Promise<void> { files.value = await listFiles() }

async function selectFile(path: string): Promise<void> {
  await flushSave()
  activePath.value = path
  if (isTextPath(path)) editorValue.value = await readText(path)
  else editorValue.value = ''
  dirty.value = false
}

async function flushSave(): Promise<void> {
  if (!dirty.value || !activeFile.value?.text) return
  if (saveTimer) clearTimeout(saveTimer)
  await writeText(activePath.value, editorValue.value)
  dirty.value = false
  await refreshFiles()
}

function queueSaveAndBuild(): void {
  dirty.value = true
  if (saveTimer) clearTimeout(saveTimer)
  saveTimer = setTimeout(async () => {
    await flushSave()
    if (autoCompile.value) queueCompile()
  }, 350)
}

function queueCompile(): void {
  if (compileTimer) clearTimeout(compileTimer)
  compileTimer = setTimeout(compileProject, 250)
}

async function compileProject(): Promise<void> {
  const generation = ++buildGeneration
  status.value = 'building'
  statusText.value = 'Compiling'
  try {
    await flushSave()
    const currentFiles = await listFiles()
    const result = await compiler.compile(currentFiles, { mainFile: '/main.tex', canvasWidth: canvasWidth.value })
    if (generation !== buildGeneration) return
    preview.value = result.output
    syncMap.value = result.syncMap
    status.value = 'ready'
    statusText.value = `Built in ${Math.round(result.duration)} ms`
  } catch (error) {
    if (generation !== buildGeneration) return
    status.value = 'error'
    statusText.value = 'Build failed'
    preview.value = error instanceof Error ? error.message : String(error)
  }
}

function outputLineAt(event: MouseEvent): number {
  const pre = previewPreRef.value
  if (!pre) return 0
  const style = window.getComputedStyle(pre)
  const lineHeight = Number.parseFloat(style.lineHeight) || Number.parseFloat(style.fontSize) * 1.2
  return Math.max(0, Math.min(syncMap.value.outputToSource.length - 1,
    Math.floor((event.clientY - pre.getBoundingClientRect().top) / lineHeight)))
}

async function revealSource(event: MouseEvent): Promise<void> {
  const location = syncMap.value.outputToSource[outputLineAt(event)]
  if (!location) return
  if (activePath.value !== location.path) {
    await selectFile(location.path)
    await nextTick()
  }
  monacoPaneRef.value?.goToLine(location.line + 1)
}

function revealOutput(sourceLine: number): void {
  const stage = paperStageRef.value
  const pre = previewPreRef.value
  const outputLine = syncMap.value.sourceToOutput[activePath.value]?.[sourceLine - 1]
  if (!stage || !pre || outputLine === undefined) return
  const style = window.getComputedStyle(pre)
  const lineHeight = Number.parseFloat(style.lineHeight) || Number.parseFloat(style.fontSize) * 1.2
  stage.scrollTo({
    top: Math.max(0, pre.offsetTop + outputLine * lineHeight - stage.clientHeight * 0.35),
    behavior: 'smooth',
  })
}

async function createFile(): Promise<void> {
  const name = window.prompt('New file name', 'chapter.tex')?.trim()
  if (!name) return
  const path = `/${name.replace(/^\/+/, '')}`
  if (files.value.some(file => file.path === path)) return void window.alert('That file already exists.')
  await writeText(path, '')
  await refreshFiles()
  await selectFile(path)
}

async function uploadFiles(event: Event): Promise<void> {
  const input = event.target as HTMLInputElement
  for (const file of Array.from(input.files ?? [])) {
    await writeBinary(`/${file.name}`, new Uint8Array(await file.arrayBuffer()))
  }
  input.value = ''
  await refreshFiles()
  queueCompile()
}

async function renameActive(): Promise<void> {
  if (!activeFile.value) return
  const name = window.prompt('Rename file', shortName(activePath.value))?.trim()
  if (!name) return
  const next = `/${name.replace(/^\/+/, '')}`
  await flushSave()
  await renameFile(activePath.value, next)
  activePath.value = next
  await refreshFiles()
  queueCompile()
}

async function deleteActive(): Promise<void> {
  if (!activeFile.value || activePath.value === '/main.tex') return
  if (!window.confirm(`Delete ${shortName(activePath.value)}?`)) return
  await removeFile(activePath.value)
  await refreshFiles()
  await selectFile('/main.tex')
  queueCompile()
}

function downloadProject(): void {
  const blob = new Blob([editorValue.value], { type: 'text/plain;charset=utf-8' })
  const anchor = document.createElement('a')
  anchor.href = URL.createObjectURL(blob)
  anchor.download = shortName(activePath.value)
  anchor.click()
  URL.revokeObjectURL(anchor.href)
}

function startResize(event: PointerEvent): void {
  if (!workspaceRef.value || window.innerWidth <= 980) return
  event.preventDefault()
  const bounds = workspaceRef.value.getBoundingClientRect()
  document.body.classList.add('is-resizing')

  const move = (moveEvent: PointerEvent) => {
    const sidebarWidth = sidebarOpen.value ? 248 : 0
    const available = bounds.width - sidebarWidth - 8
    editorWidth.value = Math.round(Math.min(Math.max(moveEvent.clientX - bounds.left - sidebarWidth, 320), available - 380))
  }
  const stop = () => {
    document.body.classList.remove('is-resizing')
    window.removeEventListener('pointermove', move)
    window.removeEventListener('pointerup', stop)
  }
  window.addEventListener('pointermove', move)
  window.addEventListener('pointerup', stop)
}

function toggleAutoCompile(): void {
  autoCompile.value = !autoCompile.value
  if (autoCompile.value) queueCompile()
  else if (status.value !== 'building') statusText.value = 'Auto compile off'
}

function toggleSidebar(): void {
  sidebarOpen.value = !sidebarOpen.value
  nextTick(() => {
    if (!workspaceRef.value || window.innerWidth <= 980) return
    const sidebarWidth = sidebarOpen.value ? 248 : 0
    const available = workspaceRef.value.clientWidth - sidebarWidth - 8
    editorWidth.value = Math.min(editorWidth.value, Math.max(320, available - 380))
  })
}

async function installApp(): Promise<void> {
  if (!installPrompt) return
  await installPrompt.prompt()
  const choice = await installPrompt.userChoice
  installAvailable.value = false
  if (choice.outcome === 'accepted') installedApp.value = true
  installPrompt = undefined
}

function captureInstallPrompt(event: Event): void {
  event.preventDefault()
  installPrompt = event as BeforeInstallPromptEvent
  installAvailable.value = true
}

function markInstalled(): void {
  installedApp.value = true
  installAvailable.value = false
  installPrompt = undefined
}

function clearTourAnchor(): void {
  document.querySelector('.tour-anchor-active')?.classList.remove('tour-anchor-active')
}

async function positionTour(): Promise<void> {
  const step = activeTour.value
  if (!step) return
  await nextTick()
  clearTourAnchor()
  const target = document.querySelector<HTMLElement>(step.target)
  if (!target) return
  target.classList.add('tour-anchor-active')
  const rect = target.getBoundingClientRect()
  const width = Math.min(310, window.innerWidth - 32)
  const gap = 14
  let placement = step.placement
  let left = rect.right + gap
  let top = rect.top
  if (placement === 'left') left = rect.left - width - gap
  if (placement === 'bottom') {
    left = rect.left + rect.width / 2 - width / 2
    top = rect.bottom + gap
  }
  if (left + width > window.innerWidth - 12 || left < 12) {
    placement = 'bottom'
    left = rect.left + rect.width / 2 - width / 2
    top = rect.bottom + gap
  }
  left = Math.max(12, Math.min(left, window.innerWidth - width - 12))
  top = Math.max(12, Math.min(top, window.innerHeight - 210))
  tourPlacement.value = placement
  tourStyle.value = { left: `${Math.round(left)}px`, top: `${Math.round(top)}px`, width: `${Math.round(width)}px` }
}

function startTour(): void {
  tourStep.value = 0
  positionTour()
}

function finishTour(): void {
  clearTourAnchor()
  tourStep.value = -1
  localStorage.setItem(tourStorageKey, '1')
}

function nextTour(): void {
  if (tourStep.value >= tourSteps.length - 1) finishTour()
  else {
    tourStep.value += 1
    positionTour()
  }
}

function previousTour(): void {
  if (tourStep.value > 0) {
    tourStep.value -= 1
    positionTour()
  }
}

async function copyOutput(): Promise<void> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(preview.value)
    } else {
      throw new Error('Clipboard API unavailable')
    }
    copyState.value = 'copied'
  } catch {
    const field = document.createElement('textarea')
    field.value = preview.value
    field.setAttribute('readonly', '')
    field.style.position = 'fixed'
    field.style.opacity = '0'
    document.body.appendChild(field)
    field.select()
    const copied = document.execCommand('copy')
    field.remove()
    copyState.value = copied ? 'copied' : 'error'
  }
  window.setTimeout(() => { copyState.value = 'idle' }, 1800)
}

watch(canvasWidth, () => { if (autoCompile.value) queueCompile() })

onMounted(async () => {
  installedApp.value = window.matchMedia('(display-mode: standalone)').matches
  window.addEventListener('beforeinstallprompt', captureInstallPrompt)
  window.addEventListener('appinstalled', markInstalled)
  window.addEventListener('resize', positionTour)
  await nextTick()
  if (!localStorage.getItem(tourStorageKey)) startTour()
  try {
    await initProjectFs()
    await refreshFiles()
    await selectFile('/main.tex')
    await compiler.initialize()
    status.value = 'ready'
    statusText.value = 'Runtime ready'
    await nextTick()
    if (workspaceRef.value && window.innerWidth > 980) {
      const usable = workspaceRef.value.clientWidth - 248 - 8
      editorWidth.value = Math.round(usable * 0.47)
    }
    await compileProject()
  } catch (error) {
    status.value = 'error'
    statusText.value = 'Startup failed'
    preview.value = error instanceof Error ? error.message : String(error)
  }
})

onBeforeUnmount(() => {
  if (saveTimer) clearTimeout(saveTimer)
  if (compileTimer) clearTimeout(compileTimer)
  window.removeEventListener('beforeinstallprompt', captureInstallPrompt)
  window.removeEventListener('appinstalled', markInstalled)
  window.removeEventListener('resize', positionTour)
  clearTourAnchor()
})
</script>

<template>
  <main class="studio">
    <header class="topbar">
      <div class="brand">
        <button class="icon-button mobile-only" aria-label="Toggle files" @click="toggleSidebar">☰</button>
        <div class="brand-mark" aria-hidden="true"><span class="brand-a">A</span><span class="brand-tau">τ</span></div>
        <div><strong>AsciiTeX</strong><small>STUDIO</small></div>
      </div>
      <div class="document-title">
        <span class="project-pill">PROJECT</span>
        <strong>Browser document</strong>
        <span class="saved-state">{{ dirty ? 'Saving…' : 'Saved locally' }}</span>
        <nav class="utility-links" aria-label="Project links">
          <button class="utility-tour" type="button" @click="startTour">Tour</button>
          <a :href="githubUrl" target="_blank" rel="noreferrer">GitHub</a>
          <a :href="imprintUrl" target="_blank" rel="noreferrer">Impressum</a>
        </nav>
      </div>
      <div class="top-actions" data-tour="actions">
        <button v-if="installAvailable && !installedApp" class="secondary-button install-button" @click="installApp">Install app</button>
        <button
          class="auto-toggle" :class="{ active: autoCompile }"
          :aria-pressed="autoCompile" @click="toggleAutoCompile"
        ><span class="toggle-track"><i /></span> Auto compile</button>
        <button class="secondary-button" @click="downloadProject">Export file</button>
        <button class="compile-button" :disabled="status === 'building'" @click="compileProject">
          <span>▶</span> Compile
        </button>
      </div>
    </header>

    <section
      ref="workspaceRef" class="workspace" :class="{ 'sidebar-closed': !sidebarOpen }"
      :style="{ '--editor-width': `${editorWidth}px` }"
    >
      <button
        class="sidebar-rail-toggle" :aria-label="sidebarOpen ? 'Collapse files' : 'Expand files'"
        :title="sidebarOpen ? 'Collapse files' : 'Expand files'" @click="toggleSidebar"
      >{{ sidebarOpen ? '‹' : '›' }}</button>
      <aside class="file-panel" data-tour="files">
        <div class="panel-heading">
          <div><span class="eyebrow">PROJECT</span><h2>Files</h2></div>
          <div class="file-actions">
            <button title="New file" @click="createFile">＋</button>
            <label title="Upload files">⇧<input type="file" multiple hidden @change="uploadFiles" /></label>
          </div>
        </div>
        <div class="file-list">
          <button
            v-for="file in files" :key="file.path"
            class="file-row" :class="{ active: file.path === activePath }"
            @click="selectFile(file.path)"
          >
            <span class="file-icon" :class="iconFor(file.path).toLowerCase()">{{ iconFor(file.path) }}</span>
            <span class="file-name">{{ shortName(file.path) }}</span>
            <span v-if="file.path === '/main.tex'" class="main-tag">MAIN</span>
          </button>
        </div>
        <div class="file-footer">
          <button @click="renameActive">Rename</button>
          <button :disabled="activePath === '/main.tex'" @click="deleteActive">Delete</button>
        </div>
      </aside>

      <section class="editor-panel" data-tour="editor">
        <div class="pane-bar">
          <div class="tab active-tab"><span>{{ iconFor(activePath) }}</span>{{ shortName(activePath) }}</div>
          <span class="pane-meta">{{ language.toUpperCase() }}</span>
        </div>
        <div v-if="activeFile?.text" class="editor-wrap">
          <MonacoPane
            ref="monacoPaneRef"
            v-model="editorValue"
            :language="language"
            @change="queueSaveAndBuild"
            @line-dblclick="revealOutput"
          />
        </div>
        <div v-else class="binary-placeholder">
          <div class="binary-icon">{{ iconFor(activePath) }}</div>
          <h3>{{ shortName(activePath) }}</h3>
          <p>Binary assets are stored in BrowserFS and available to AsciiTeX.</p>
        </div>
      </section>

      <div
        class="pane-splitter" role="separator" aria-label="Resize editor and preview"
        data-tour="splitter"
        aria-orientation="vertical" :aria-valuenow="editorWidth"
        @pointerdown="startResize"
      ><span /></div>

      <section class="preview-panel" data-tour="preview">
        <div class="pane-bar preview-bar">
          <div><span class="eyebrow">OUTPUT</span><strong>Unicode preview</strong></div>
          <div class="preview-controls">
            <label class="width-control" title="AsciiTeX canvas width in characters">
              <span>Document width</span>
              <input v-model.number="canvasWidth" class="width-slider" type="range" min="48" max="160" step="2" />
              <input v-model.number="canvasWidth" class="width-number" type="number" min="48" max="160" />
              <small>chars</small>
            </label>
            <button class="copy-button" type="button" title="Copy Unicode output to clipboard" @click="copyOutput">
              {{ copyState === 'copied' ? '✓ Copied' : copyState === 'error' ? 'Copy failed' : '⧉ Copy output' }}
            </button>
            <span class="status-dot" :class="status"></span>
            <span>{{ statusText }}</span>
          </div>
        </div>
        <div ref="paperStageRef" class="paper-stage">
          <div class="paper">
            <pre ref="previewPreRef" title="Double-click to reveal this line in its source file" @dblclick="revealSource">{{ preview }}</pre>
          </div>
        </div>
      </section>
    </section>

    <aside
      v-if="activeTour" class="tour-bubble" :class="`tour-${tourPlacement}`"
      :style="tourStyle" role="dialog" aria-live="polite" aria-label="AsciiTeX Studio guided tour"
    >
      <div class="tour-progress">{{ tourStep + 1 }} / {{ tourSteps.length }}</div>
      <h2>{{ activeTour.title }}</h2>
      <p>{{ activeTour.text }}</p>
      <div class="tour-actions">
        <button class="tour-skip" type="button" @click="finishTour">Skip</button>
        <button v-if="tourStep > 0" type="button" @click="previousTour">Back</button>
        <button class="tour-next" type="button" @click="nextTour">{{ tourStep === tourSteps.length - 1 ? 'Done' : 'Next' }}</button>
      </div>
    </aside>
  </main>
</template>
