<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { zipSync } from 'fflate'
import MonacoPane from './MonacoPane.vue'
import {
  initProjectFs, isTextPath, listFiles, readText, removeFile, renameFile,
  writeBinary, writeText, type ProjectFile,
} from './projectFs'
import { AsciiTeXCompiler } from './compiler'
import type { SourceSyncMap } from './syncMap'

const files = ref<ProjectFile[]>([])
const activePath = ref('/main.tex')
const editorValue = ref('')
const preview = ref('Starting AsciiTeX…')
const status = ref<'loading' | 'ready' | 'building' | 'error'>('loading')
const statusText = ref('Loading Pyodide')
const canvasWidth = ref(96)
const sidebarOpen = ref(true)
const autoCompile = ref(true)
const editorWidth = ref(520)
const workspaceRef = ref<HTMLElement>()
const monacoPaneRef = ref<InstanceType<typeof MonacoPane>>()
const paperStageRef = ref<HTMLElement>()
const previewPreRef = ref<HTMLElement>()
const syncMap = ref<SourceSyncMap>({ outputToSource: [], sourceToOutput: {} })
const copyState = ref<'idle' | 'copied' | 'error'>('idle')
const dirty = ref(false)
const installAvailable = ref(false)
const installedApp = ref(false)
const fileDragActive = ref(false)
const previewPoppedOut = ref(false)
const tourStep = ref(-1)
const tourStyle = ref<Record<string, string>>({})
const tourPlacement = ref<'right' | 'left' | 'bottom'>('right')
const fileMenu = ref<{ path: string; x: number; y: number } | null>(null)
const compiler = new AsciiTeXCompiler()
let installPrompt: BeforeInstallPromptEvent | undefined
let saveTimer: ReturnType<typeof setTimeout> | undefined
let compileTimer: ReturnType<typeof setTimeout> | undefined
let dragDepth = 0
let buildGeneration = 0
let previewWindow: Window | null = null

interface BeforeInstallPromptEvent extends Event {
  prompt(): Promise<void>
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed'; platform: string }>
}

// Published project and legal links.
const githubUrl = 'https://github.com/thomasliebig/asciitexstudio'
const imprintUrl = 'https://tapekuna.ai/#impressum'
const tourStorageKey = 'asciitex-studio-tour-complete-v1'
const tourSteps = [
  { target: '[data-tour="files"]', placement: 'right' as const, title: 'Your project files', text: 'Manage the main TeX document, bibliography, images, and other assets here. Everything stays locally in your browser.' },
  { target: '[data-tour="editor"]', placement: 'bottom' as const, title: 'Write AsciiTeX', text: 'Edit the selected text file in Monaco. Syntax highlighting and automatic compilation help you iterate quickly.' },
  { target: '[data-tour="splitter"]', placement: 'left' as const, title: 'Make room where needed', text: 'Drag this divider horizontally to balance source code and rendered output.' },
  { target: '[data-tour="preview"]', placement: 'bottom' as const, title: 'Unicode output', text: 'The result is generated by AsciiTeX in Pyodide. Double-click output and source lines to jump between them.' },
  { target: '[data-tour="actions"]', placement: 'bottom' as const, title: 'Compile and export', text: 'Toggle automatic compilation, compile manually, export the active file, or install the studio as a browser app.' },
]
const activeTour = computed(() => tourStep.value >= 0 ? tourSteps[tourStep.value] : undefined)

const activeFile = computed(() => files.value.find(file => file.path === activePath.value))
const texFiles = computed(() => files.value.filter(file => file.path.endsWith('.tex')))
const language = computed(() => {
  const extension = activePath.value.split('.').pop()?.toLowerCase()
  return ({ tex: 'asciitex', bib: 'bibtex', json: 'json', py: 'python', md: 'markdown' } as Record<string, string>)[extension ?? ''] ?? 'plaintext'
})

function iconFor(path: string): string {
  const ext = path.split('.').pop()?.toLowerCase()
  if (ext === 'tex') return 'TEX'
  if (ext === 'bib') return 'BIB'
  if (['png', 'jpg', 'jpeg', 'gif', 'webp'].includes(ext ?? '')) return 'IMG'
  return 'TXT'
}

function shortName(path: string): string { return path.replace(/^\//, '') }

async function refreshFiles(): Promise<void> { files.value = await listFiles() }

async function selectFile(path: string): Promise<void> {
  await flushSave()
  activePath.value = path
  if (isTextPath(path)) editorValue.value = await readText(path)
  else editorValue.value = ''
  dirty.value = false
}

async function flushSave(): Promise<void> {
  if (!dirty.value || !activeFile.value?.text) return
  if (saveTimer) clearTimeout(saveTimer)
  await writeText(activePath.value, editorValue.value)
  dirty.value = false
  await refreshFiles()
}

function queueSaveAndBuild(): void {
  dirty.value = true
  if (saveTimer) clearTimeout(saveTimer)
  saveTimer = setTimeout(async () => {
    await flushSave()
    if (autoCompile.value) queueCompile()
  }, 350)
}

function queueCompile(): void {
  if (compileTimer) clearTimeout(compileTimer)
  compileTimer = setTimeout(compileProject, 250)
}

async function compileProject(): Promise<void> {
  const generation = ++buildGeneration
  status.value = 'building'
  statusText.value = 'Compiling'
  try {
    await flushSave()
    const currentFiles = await listFiles()
    const result = await compiler.compile(currentFiles, { mainFile: '/main.tex', canvasWidth: canvasWidth.value })
    if (generation !== buildGeneration) return
    preview.value = result.output
    syncMap.value = result.syncMap
    status.value = 'ready'
    statusText.value = `Built in ${Math.round(result.duration)} ms`
  } catch (error) {
    if (generation !== buildGeneration) return
    status.value = 'error'
    statusText.value = 'Build failed'
    preview.value = error instanceof Error ? error.message : String(error)
  }
}

function outputLineAt(event: MouseEvent): number {
  const pre = previewPreRef.value
  if (!pre) return 0
  const style = window.getComputedStyle(pre)
  const lineHeight = Number.parseFloat(style.lineHeight) || Number.parseFloat(style.fontSize) * 1.2
  return Math.max(0, Math.min(syncMap.value.outputToSource.length - 1,
    Math.floor((event.clientY - pre.getBoundingClientRect().top) / lineHeight)))
}

async function revealSource(event: MouseEvent): Promise<void> {
  const location = syncMap.value.outputToSource[outputLineAt(event)]
  if (!location) return
  if (activePath.value !== location.path) {
    await selectFile(location.path)
    await nextTick()
  }
  monacoPaneRef.value?.goToLine(location.line + 1)
}

function revealOutput(sourceLine: number): void {
  const stage = paperStageRef.value
  const pre = previewPreRef.value
  const outputLine = syncMap.value.sourceToOutput[activePath.value]?.[sourceLine - 1]
  if (!stage || !pre || outputLine === undefined) return
  const style = window.getComputedStyle(pre)
  const lineHeight = Number.parseFloat(style.lineHeight) || Number.parseFloat(style.fontSize) * 1.2
  stage.scrollTo({
    top: Math.max(0, pre.offsetTop + outputLine * lineHeight - stage.clientHeight * 0.35),
    behavior: 'smooth',
  })
}

async function createFile(): Promise<void> {
  const name = window.prompt('New file name', 'chapter.tex')?.trim()
  if (!name) return
  const path = `/${name.replace(/^\/+/, '')}`
  if (files.value.some(file => file.path === path)) return void window.alert('That file already exists.')
  await writeText(path, '')
  await refreshFiles()
  await selectFile(path)
}

async function uploadFiles(event: Event): Promise<void> {
  const input = event.target as HTMLInputElement
  await writeDroppedFiles(Array.from(input.files ?? []))
  input.value = ''
}

async function writeDroppedFiles(droppedFiles: File[]): Promise<void> {
  if (!droppedFiles.length) return
  await flushSave()
  for (const file of droppedFiles) {
    const relative = (file as File & { webkitRelativePath?: string }).webkitRelativePath || file.name
    const path = `/${relative.replace(/^\/+/, '').replaceAll('\\', '/')}`
    await writeBinary(path, new Uint8Array(await file.arrayBuffer()))
  }
  await refreshFiles()
  const firstText = droppedFiles
    .map(file => `/${(((file as File & { webkitRelativePath?: string }).webkitRelativePath || file.name).replace(/^\/+/, '').replaceAll('\\', '/'))}`)
    .find(path => isTextPath(path))
  if (firstText) await selectFile(firstText)
  queueCompile()
}

function onFileDragEnter(event: DragEvent): void {
  if (!event.dataTransfer?.types.includes('Files')) return
  event.preventDefault()
  dragDepth += 1
  fileDragActive.value = true
}

function onFileDragOver(event: DragEvent): void {
  if (!event.dataTransfer?.types.includes('Files')) return
  event.preventDefault()
  event.dataTransfer.dropEffect = 'copy'
  fileDragActive.value = true
}

function onFileDragLeave(event: DragEvent): void {
  if (!event.dataTransfer?.types.includes('Files')) return
  dragDepth = Math.max(0, dragDepth - 1)
  if (dragDepth === 0) fileDragActive.value = false
}

async function onFileDrop(event: DragEvent): Promise<void> {
  if (!event.dataTransfer?.files.length) return
  event.preventDefault()
  dragDepth = 0
  fileDragActive.value = false
  await writeDroppedFiles(Array.from(event.dataTransfer.files))
}

async function renamePath(path = activePath.value): Promise<void> {
  const name = window.prompt('Rename file', shortName(path))?.trim()
  if (!name) return
  const next = `/${name.replace(/^\/+/, '')}`
  if (next !== path && files.value.some(file => file.path === next)) return void window.alert('That file already exists.')
  await flushSave()
  await renameFile(path, next)
  if (activePath.value === path) activePath.value = next
  await refreshFiles()
  queueCompile()
}

async function deletePath(path = activePath.value): Promise<void> {
  if (path === '/main.tex') return
  if (!window.confirm(`Delete ${shortName(path)}?`)) return
  await removeFile(path)
  await refreshFiles()
  if (activePath.value === path) await selectFile('/main.tex')
  queueCompile()
}

function saveBlob(blob: Blob, name: string): void {
  const anchor = document.createElement('a')
  anchor.href = URL.createObjectURL(blob)
  anchor.download = name
  anchor.click()
  URL.revokeObjectURL(anchor.href)
}

async function downloadFile(path = activePath.value): Promise<void> {
  if (path === activePath.value) await flushSave()
  const file = (await listFiles()).find(candidate => candidate.path === path)
  if (!file) return
  saveBlob(new Blob([file.data as BlobPart], { type: file.text ? 'text/plain;charset=utf-8' : 'application/octet-stream' }), shortName(path))
}

async function downloadProjectZip(): Promise<void> {
  await flushSave()
  const archive: Record<string, Uint8Array> = {}
  for (const file of await listFiles()) archive[shortName(file.path)] = file.data
  saveBlob(new Blob([zipSync(archive, { level: 6 }) as BlobPart], { type: 'application/zip' }), 'asciitex-project.zip')
}

async function duplicateFile(path = activePath.value): Promise<void> {
  if (path === activePath.value) await flushSave()
  const source = (await listFiles()).find(file => file.path === path)
  if (!source) return
  const name = shortName(path)
  const dot = name.lastIndexOf('.')
  const stem = dot > 0 ? name.slice(0, dot) : name
  const extension = dot > 0 ? name.slice(dot) : ''
  let index = 1
  let next = `/${stem} copy${extension}`
  while (files.value.some(file => file.path === next)) next = `/${stem} copy ${++index}${extension}`
  await writeBinary(next, source.data)
  await refreshFiles()
  await selectFile(next)
  queueCompile()
}

function openFileMenu(event: MouseEvent, path: string): void {
  event.preventDefault()
  const width = 174
  const height = 170
  fileMenu.value = {
    path,
    x: Math.max(8, Math.min(event.clientX, window.innerWidth - width - 8)),
    y: Math.max(8, Math.min(event.clientY, window.innerHeight - height - 8)),
  }
}

function closeFileMenu(): void { fileMenu.value = null }

async function runFileAction(action: 'rename' | 'duplicate' | 'download' | 'delete'): Promise<void> {
  const path = fileMenu.value?.path
  closeFileMenu()
  if (!path) return
  if (action === 'rename') await renamePath(path)
  if (action === 'duplicate') await duplicateFile(path)
  if (action === 'download') await downloadFile(path)
  if (action === 'delete') await deletePath(path)
}

function startResize(event: PointerEvent): void {
  if (!workspaceRef.value || window.innerWidth <= 980) return
  event.preventDefault()
  const bounds = workspaceRef.value.getBoundingClientRect()
  document.body.classList.add('is-resizing')

  const move = (moveEvent: PointerEvent) => {
    const sidebarWidth = sidebarOpen.value ? 248 : 0
    const available = bounds.width - sidebarWidth - 8
    editorWidth.value = Math.round(Math.min(Math.max(moveEvent.clientX - bounds.left - sidebarWidth, 320), available - 380))
  }
  const stop = () => {
    document.body.classList.remove('is-resizing')
    window.removeEventListener('pointermove', move)
    window.removeEventListener('pointerup', stop)
  }
  window.addEventListener('pointermove', move)
  window.addEventListener('pointerup', stop)
}

function toggleAutoCompile(): void {
  autoCompile.value = !autoCompile.value
  if (autoCompile.value) queueCompile()
  else if (status.value !== 'building') statusText.value = 'Auto compile off'
}

function toggleSidebar(): void {
  sidebarOpen.value = !sidebarOpen.value
  nextTick(() => {
    if (!workspaceRef.value || window.innerWidth <= 980) return
    const sidebarWidth = sidebarOpen.value ? 248 : 0
    const available = workspaceRef.value.clientWidth - sidebarWidth - 8
    editorWidth.value = Math.min(editorWidth.value, Math.max(320, available - 380))
  })
}

async function installApp(): Promise<void> {
  if (!installPrompt) return
  await installPrompt.prompt()
  const choice = await installPrompt.userChoice
  installAvailable.value = false
  if (choice.outcome === 'accepted') installedApp.value = true
  installPrompt = undefined
}

function captureInstallPrompt(event: Event): void {
  event.preventDefault()
  installPrompt = event as BeforeInstallPromptEvent
  installAvailable.value = true
}

function markInstalled(): void {
  installedApp.value = true
  installAvailable.value = false
  installPrompt = undefined
}

function clearTourAnchor(): void {
  document.querySelector('.tour-anchor-active')?.classList.remove('tour-anchor-active')
}

async function positionTour(): Promise<void> {
  const step = activeTour.value
  if (!step) return
  await nextTick()
  clearTourAnchor()
  const target = document.querySelector<HTMLElement>(step.target)
  if (!target) return
  target.classList.add('tour-anchor-active')
  const rect = target.getBoundingClientRect()
  const width = Math.min(310, window.innerWidth - 32)
  const gap = 14
  let placement = step.placement
  let left = rect.right + gap
  let top = rect.top
  if (placement === 'left') left = rect.left - width - gap
  if (placement === 'bottom') {
    left = rect.left + rect.width / 2 - width / 2
    top = rect.bottom + gap
  }
  if (left + width > window.innerWidth - 12 || left < 12) {
    placement = 'bottom'
    left = rect.left + rect.width / 2 - width / 2
    top = rect.bottom + gap
  }
  left = Math.max(12, Math.min(left, window.innerWidth - width - 12))
  top = Math.max(12, Math.min(top, window.innerHeight - 210))
  tourPlacement.value = placement
  tourStyle.value = { left: `${Math.round(left)}px`, top: `${Math.round(top)}px`, width: `${Math.round(width)}px` }
}

function startTour(): void {
  tourStep.value = 0
  positionTour()
}

function finishTour(): void {
  clearTourAnchor()
  tourStep.value = -1
  localStorage.setItem(tourStorageKey, '1')
}

function nextTour(): void {
  if (tourStep.value >= tourSteps.length - 1) finishTour()
  else {
    tourStep.value += 1
    positionTour()
  }
}

function previousTour(): void {
  if (tourStep.value > 0) {
    tourStep.value -= 1
    positionTour()
  }
}

async function copyOutput(): Promise<void> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(preview.value)
    } else {
      throw new Error('Clipboard API unavailable')
    }
    copyState.value = 'copied'
  } catch {
    const field = document.createElement('textarea')
    field.value = preview.value
    field.setAttribute('readonly', '')
    field.style.position = 'fixed'
    field.style.opacity = '0'
    document.body.appendChild(field)
    field.select()
    const copied = document.execCommand('copy')
    field.remove()
    copyState.value = copied ? 'copied' : 'error'
  }
  window.setTimeout(() => { copyState.value = 'idle' }, 1800)
}

function escapeHtml(text: string): string {
  return text.replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch] ?? ch))
}

function popoutCss(): string {
  const base = import.meta.env.BASE_URL
  const fontUrl = `${window.location.origin}${base}fonts/NotoSansMono-Variable.ttf`
  return `
    @font-face { font-family: 'AsciiTeX Unicode Mono'; src: url('${fontUrl}') format('truetype'); font-display: block; }
    * { box-sizing: border-box; }
    body { margin: 0; min-height: 100vh; background: #0b130e; color: #d8f2df; font-family: 'DM Sans', system-ui, sans-serif; }
    .popout-shell { min-height: 100vh; display: grid; grid-template-rows: 42px 1fr; background:
      radial-gradient(circle at 20% 0%, #1d3b28 0, transparent 34%),
      linear-gradient(135deg, #0c160f 0%, #13231a 58%, #0a110d 100%); }
    .popout-bar { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 0 13px; border-bottom: 1px solid #31523d; background: #132019e8; color: #9fcfab; }
    .popout-title { display: flex; align-items: center; gap: 8px; font-size: 11px; letter-spacing: .14em; text-transform: uppercase; }
    .popout-title i { width: 8px; height: 8px; border-radius: 50%; background: #7ee097; box-shadow: 0 0 12px #7ee09799; }
    .popout-actions { display: flex; align-items: center; gap: 10px; font-size: 11px; }
    button { height: 28px; padding: 0 10px; border: 1px solid #5b8e68; border-radius: 3px; color: #dff7e6; background: #1a3323; cursor: pointer; }
    button:hover { background: #24452f; border-color: #8be7a0; }
    .popout-stage { overflow: auto; padding: 24px; }
    .popout-paper { min-width: max-content; min-height: 100%; padding: 30px 32px; border: 1px solid #bad3bd; background: #eef5e9; box-shadow: 0 0 0 1px #ffffff55 inset, 0 18px 54px #0008; }
    pre { margin: 0; color: #101d15; font-family: 'AsciiTeX Unicode Mono', monospace; font-size: 12px; line-height: 1.28; font-variant-ligatures: none; font-feature-settings: 'liga' 0, 'calt' 0; white-space: pre; }
  `
}

function updatePopoutPreview(): void {
  if (!previewWindow || previewWindow.closed) {
    previewWindow = null
    previewPoppedOut.value = false
    return
  }
  const pre = previewWindow.document.getElementById('preview-output')
  const statusLabel = previewWindow.document.getElementById('preview-status')
  const widthLabel = previewWindow.document.getElementById('preview-width')
  if (pre) pre.textContent = preview.value
  if (statusLabel) statusLabel.textContent = statusText.value
  if (widthLabel) widthLabel.textContent = `${canvasWidth.value} chars`
}

function openPreviewPopout(): void {
  if (previewWindow && !previewWindow.closed) {
    previewWindow.focus()
    return
  }
  previewWindow = window.open('', 'asciitex-preview', 'popup=yes,width=980,height=760')
  if (!previewWindow) {
    window.alert('The browser blocked the preview pop-out. Please allow pop-ups for this site.')
    return
  }
  previewWindow.document.open()
  previewWindow.document.write(`<!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>AsciiTeX Live Preview</title>
        <style>${popoutCss()}</style>
      </head>
      <body>
        <main class="popout-shell">
          <header class="popout-bar">
            <div class="popout-title"><i></i><strong>AsciiTeX live preview</strong></div>
            <div class="popout-actions"><span id="preview-width">${canvasWidth.value} chars</span><span id="preview-status">${escapeHtml(statusText.value)}</span><button onclick="window.close()">Dock in</button></div>
          </header>
          <section class="popout-stage">
            <div class="popout-paper"><pre id="preview-output"></pre></div>
          </section>
        </main>
      </body>
    </html>`)
  previewWindow.document.close()
  previewWindow.addEventListener('beforeunload', () => {
    previewWindow = null
    previewPoppedOut.value = false
  })
  previewPoppedOut.value = true
  updatePopoutPreview()
  previewWindow.focus()
}

function dockPreview(): void {
  if (previewWindow && !previewWindow.closed) previewWindow.close()
  previewWindow = null
  previewPoppedOut.value = false
}

function togglePreviewPopout(): void {
  if (previewPoppedOut.value) dockPreview()
  else openPreviewPopout()
}

watch(canvasWidth, () => { if (autoCompile.value) queueCompile() })
watch([preview, statusText, canvasWidth], updatePopoutPreview)

onMounted(async () => {
  installedApp.value = window.matchMedia('(display-mode: standalone)').matches
  window.addEventListener('beforeinstallprompt', captureInstallPrompt)
  window.addEventListener('appinstalled', markInstalled)
  window.addEventListener('resize', positionTour)
  window.addEventListener('click', closeFileMenu)
  window.addEventListener('blur', closeFileMenu)
  await nextTick()
  if (!localStorage.getItem(tourStorageKey)) startTour()
  try {
    await initProjectFs()
    await refreshFiles()
    await selectFile('/main.tex')
    await compiler.initialize()
    status.value = 'ready'
    statusText.value = 'Runtime ready'
    await nextTick()
    if (workspaceRef.value && window.innerWidth > 980) {
      const usable = workspaceRef.value.clientWidth - 248 - 8
      editorWidth.value = Math.round(usable * 0.47)
    }
    await compileProject()
  } catch (error) {
    status.value = 'error'
    statusText.value = 'Startup failed'
    preview.value = error instanceof Error ? error.message : String(error)
  }
})

onBeforeUnmount(() => {
  if (saveTimer) clearTimeout(saveTimer)
  if (compileTimer) clearTimeout(compileTimer)
  dockPreview()
  window.removeEventListener('beforeinstallprompt', captureInstallPrompt)
  window.removeEventListener('appinstalled', markInstalled)
  window.removeEventListener('resize', positionTour)
  window.removeEventListener('click', closeFileMenu)
  window.removeEventListener('blur', closeFileMenu)
  clearTourAnchor()
})
</script>

<template>
  <main class="studio">
    <header class="topbar">
      <div class="brand">
        <button class="icon-button mobile-only" aria-label="Toggle files" @click="toggleSidebar">☰</button>
        <div class="brand-mark" aria-hidden="true"><span class="brand-a">A</span><span class="brand-tau">τ</span></div>
        <div><strong>AsciiTeX</strong><small>STUDIO</small></div>
      </div>
      <div class="document-title">
        <span class="project-pill">PROJECT</span>
        <strong>Browser document</strong>
        <span class="saved-state">{{ dirty ? 'Saving…' : 'Saved locally' }}</span>
        <nav class="utility-links" aria-label="Project links">
          <button class="utility-tour" type="button" @click="startTour">Tour</button>
          <a :href="githubUrl" target="_blank" rel="noreferrer">GitHub</a>
          <a :href="imprintUrl" target="_blank" rel="noreferrer">Impressum</a>
        </nav>
      </div>
      <div class="top-actions" data-tour="actions">
        <button v-if="installAvailable && !installedApp" class="secondary-button install-button" @click="installApp">Install app</button>
        <button
          class="auto-toggle" :class="{ active: autoCompile }"
          :aria-pressed="autoCompile" @click="toggleAutoCompile"
        ><span class="toggle-track"><i /></span> Auto compile</button>
        <button class="secondary-button" @click="downloadFile()">Download file</button>
        <button class="compile-button" :disabled="status === 'building'" @click="compileProject">
          <span>▶</span> Compile
        </button>
      </div>
    </header>

    <section
      ref="workspaceRef" class="workspace" :class="{ 'sidebar-closed': !sidebarOpen }"
      :style="{ '--editor-width': `${editorWidth}px` }"
    >
      <button
        class="sidebar-rail-toggle" :aria-label="sidebarOpen ? 'Collapse files' : 'Expand files'"
        :title="sidebarOpen ? 'Collapse files' : 'Expand files'" @click="toggleSidebar"
      >{{ sidebarOpen ? '‹' : '›' }}</button>
      <aside
        class="file-panel" :class="{ 'drag-active': fileDragActive }" data-tour="files"
        @dragenter="onFileDragEnter" @dragover="onFileDragOver" @dragleave="onFileDragLeave" @drop="onFileDrop"
      >
        <div class="panel-heading">
          <div><span class="eyebrow">PROJECT</span><h2>Files</h2></div>
          <div class="file-actions">
            <button title="New file" @click="createFile">＋</button>
            <label title="Upload files">⇧<input type="file" multiple hidden @change="uploadFiles" /></label>
            <button title="Download project as ZIP" @click="downloadProjectZip">ZIP</button>
          </div>
        </div>
        <div class="file-list">
          <div
            v-for="file in files" :key="file.path"
            class="file-row" :class="{ active: file.path === activePath }"
            role="button" tabindex="0"
            @click="selectFile(file.path)" @keydown.enter="selectFile(file.path)"
            @contextmenu="openFileMenu($event, file.path)"
          >
            <span class="file-icon" :class="iconFor(file.path).toLowerCase()">{{ iconFor(file.path) }}</span>
            <span class="file-name">{{ shortName(file.path) }}</span>
            <span v-if="file.path === '/main.tex'" class="main-tag">MAIN</span>
            <button class="file-more" :aria-label="`Actions for ${shortName(file.path)}`" title="File actions" @click.stop="openFileMenu($event, file.path)">•••</button>
          </div>
          <div class="drop-hint" aria-hidden="true">
            <span>⇣</span>
            <strong>Drop files here</strong>
            <small>.tex, .bib, images and project assets</small>
          </div>
        </div>
        <div class="file-footer">
          <span>{{ files.length }} files · stored locally</span>
          <button title="Download complete project" @click="downloadProjectZip">Download ZIP</button>
        </div>
      </aside>

      <div
        v-if="fileMenu" class="file-context-menu" role="menu"
        :style="{ left: `${fileMenu.x}px`, top: `${fileMenu.y}px` }" @click.stop
      >
        <div class="context-title">{{ shortName(fileMenu.path) }}</div>
        <button role="menuitem" @click="runFileAction('rename')"><span>✎</span> Rename</button>
        <button role="menuitem" @click="runFileAction('duplicate')"><span>⧉</span> Duplicate</button>
        <button role="menuitem" @click="runFileAction('download')"><span>↓</span> Download</button>
        <div class="context-separator" />
        <button role="menuitem" class="danger" :disabled="fileMenu.path === '/main.tex'" @click="runFileAction('delete')"><span>×</span> Delete</button>
      </div>

      <section class="editor-panel" data-tour="editor">
        <div class="pane-bar">
          <div class="tab active-tab"><span>{{ iconFor(activePath) }}</span>{{ shortName(activePath) }}</div>
          <span class="pane-meta">{{ language.toUpperCase() }}</span>
        </div>
        <div v-if="activeFile?.text" class="editor-wrap">
          <MonacoPane
            ref="monacoPaneRef"
            v-model="editorValue"
            :language="language"
            @change="queueSaveAndBuild"
            @line-dblclick="revealOutput"
          />
        </div>
        <div v-else class="binary-placeholder">
          <div class="binary-icon">{{ iconFor(activePath) }}</div>
          <h3>{{ shortName(activePath) }}</h3>
          <p>Binary assets are stored in BrowserFS and available to AsciiTeX.</p>
        </div>
      </section>

      <div
        class="pane-splitter" role="separator" aria-label="Resize editor and preview"
        data-tour="splitter"
        aria-orientation="vertical" :aria-valuenow="editorWidth"
        @pointerdown="startResize"
      ><span /></div>

      <section class="preview-panel" data-tour="preview">
        <div class="pane-bar preview-bar">
          <div><span class="eyebrow">OUTPUT</span><strong>Unicode preview</strong></div>
          <div class="preview-controls">
            <label class="width-control" title="AsciiTeX canvas width in characters">
              <span>Document width</span>
              <input v-model.number="canvasWidth" class="width-slider" type="range" min="48" max="160" step="2" />
              <input v-model.number="canvasWidth" class="width-number" type="number" min="48" max="160" />
              <small>chars</small>
            </label>
            <button class="copy-button" type="button" title="Copy Unicode output to clipboard" @click="copyOutput">
              {{ copyState === 'copied' ? '✓ Copied' : copyState === 'error' ? 'Copy failed' : '⧉ Copy output' }}
            </button>
            <button class="copy-button popout-button" type="button" :title="previewPoppedOut ? 'Dock preview back into the studio' : 'Pop out preview into a separate window'" @click="togglePreviewPopout">
              {{ previewPoppedOut ? '↙ Dock in' : '↗ Pop out' }}
            </button>
            <span class="status-dot" :class="status"></span>
            <span>{{ statusText }}</span>
          </div>
        </div>
        <div ref="paperStageRef" class="paper-stage">
          <div class="paper">
            <pre ref="previewPreRef" title="Double-click to reveal this line in its source file" @dblclick="revealSource">{{ preview }}</pre>
          </div>
        </div>
      </section>
    </section>

    <aside
      v-if="activeTour" class="tour-bubble" :class="`tour-${tourPlacement}`"
      :style="tourStyle" role="dialog" aria-live="polite" aria-label="AsciiTeX Studio guided tour"
    >
      <div class="tour-progress">{{ tourStep + 1 }} / {{ tourSteps.length }}</div>
      <h2>{{ activeTour.title }}</h2>
      <p>{{ activeTour.text }}</p>
      <div class="tour-actions">
        <button class="tour-skip" type="button" @click="finishTour">Skip</button>
        <button v-if="tourStep > 0" type="button" @click="previousTour">Back</button>
        <button class="tour-next" type="button" @click="nextTour">{{ tourStep === tourSteps.length - 1 ? 'Done' : 'Next' }}</button>
      </div>
    </aside>
  </main>
</template>
